# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='genius_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('catalyst', models.CharField(max_length=256)),
                ('foundation', models.CharField(max_length=256)),
                ('virtue', models.CharField(max_length=256)),
                ('vice', models.CharField(max_length=256)),
                ('aesthetics', models.TextField()),
                ('strength_attr', models.IntegerField()),
                ('dexterity_attr', models.IntegerField()),
                ('stamina_attr', models.IntegerField()),
                ('intelligence_attr', models.IntegerField()),
                ('wits_attr', models.IntegerField()),
                ('resolve_attr', models.IntegerField()),
                ('presence_attr', models.IntegerField()),
                ('manipulation_attr', models.IntegerField()),
                ('composure_attr', models.IntegerField()),
                ('academics_skill', models.IntegerField()),
                ('computer_skill', models.IntegerField()),
                ('crafts_skill', models.IntegerField()),
                ('investigation_skill', models.IntegerField()),
                ('medicine_skill', models.IntegerField()),
                ('occult_skill', models.IntegerField()),
                ('politics_skill', models.IntegerField()),
                ('science_skill', models.IntegerField()),
                ('athletics_skill', models.IntegerField()),
                ('brawl_skill', models.IntegerField()),
                ('drive_skill', models.IntegerField()),
                ('firearms_skill', models.IntegerField()),
                ('larceny_skill', models.IntegerField()),
                ('stealth_skill', models.IntegerField()),
                ('survival_skill', models.IntegerField()),
                ('weaponry_skill', models.IntegerField()),
                ('animal_ken_skill', models.IntegerField()),
                ('empathy_skill', models.IntegerField()),
                ('expression_skill', models.IntegerField()),
                ('intimidation_skill', models.IntegerField()),
                ('persuasion_skill', models.IntegerField()),
                ('socialize_skill', models.IntegerField()),
                ('streetwise_skill', models.IntegerField()),
                ('subterfuge_skill', models.IntegerField()),
                ('apokalypsi_axiom', models.IntegerField()),
                ('automata_axiom', models.IntegerField()),
                ('epikrato_axiom', models.IntegerField()),
                ('exelixi_axiom', models.IntegerField()),
                ('katastrofi_axiom', models.IntegerField()),
                ('metaptropi_axiom', models.IntegerField()),
                ('prostasia_axiom', models.IntegerField()),
                ('skafoi_axiom', models.IntegerField()),
                ('inspiration', models.IntegerField()),
                ('obligation', models.IntegerField()),
                ('size', models.IntegerField()),
                ('specialties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
