# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 00:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniusapp', '0002_genius_char_merits'),
    ]

    operations = [
        migrations.CreateModel(
            name='wonder_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axiom_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('wonder_type_id', models.IntegerField()),
                ('core_modifier', models.IntegerField()),
                ('notes', models.TextField()),
                ('fault', models.TextField()),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField()),
                ('genius_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geniusapp.genius_char')),
            ],
        ),
    ]
