# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniusapp', '0003_wonder_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genius_char',
            old_name='aesthetics',
            new_name='aesthetic',
        ),
    ]
