# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusapp', '0004_auto_20171115_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_char',
            name='chronicle',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_char',
            name='concept',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_char',
            name='player',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
