# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusapp', '0005_auto_20171115_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_char',
            name='armor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
