from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
# Create your models here.

class genius_char(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=256)
	catalyst = models.CharField(max_length=256)
	foundation = models.CharField(max_length=256)
	virtue = models.CharField(max_length=256)
	vice = models.CharField(max_length=256)
	aesthetics = models.TextField()
	strength_attr = models.IntegerField()
	dexterity_attr = models.IntegerField()
	stamina_attr = models.IntegerField()
	intelligence_attr = models.IntegerField()
	wits_attr = models.IntegerField()
	resolve_attr = models.IntegerField()
	presence_attr = models.IntegerField()
	manipulation_attr = models.IntegerField()
	composure_attr = models.IntegerField()
	academics_skill = models.IntegerField()
	computer_skill = models.IntegerField()
	crafts_skill = models.IntegerField()
	investigation_skill = models.IntegerField()
	medicine_skill = models.IntegerField()
	occult_skill = models.IntegerField()
	politics_skill = models.IntegerField()
	science_skill = models.IntegerField()
	athletics_skill = models.IntegerField()
	brawl_skill = models.IntegerField()
	drive_skill = models.IntegerField()
	firearms_skill = models.IntegerField()
	larceny_skill = models.IntegerField()
	stealth_skill = models.IntegerField()
	survival_skill = models.IntegerField()
	weaponry_skill = models.IntegerField()
	animal_ken_skill = models.IntegerField()
	empathy_skill = models.IntegerField()
	expression_skill = models.IntegerField()
	intimidation_skill = models.IntegerField()
	persuasion_skill = models.IntegerField()
	socialize_skill = models.IntegerField()
	streetwise_skill = models.IntegerField()
	subterfuge_skill = models.IntegerField()
	apokalypsi_axiom = models.IntegerField()
	automata_axiom = models.IntegerField()
	epikrato_axiom = models.IntegerField()
	exelixi_axiom = models.IntegerField()
	katastrofi_axiom = models.IntegerField()
	metaptropi_axiom = models.IntegerField()
	prostasia_axiom = models.IntegerField()
	skafoi_axiom = models.IntegerField()
	inspiration = models.IntegerField()
	obligation = models.IntegerField()
	size = models.IntegerField()
	specialties = JSONField()
	merits = JSONField()


